// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnG7H_WcRm5WbR-JM_8-purMln4mW9rl4',
    appId: '1:579004116235:web:8cb84740d472393882c60e',
    messagingSenderId: '579004116235',
    projectId: 'makanek-c0f6a',
    authDomain: 'makanek-c0f6a.firebaseapp.com',
    storageBucket: 'makanek-c0f6a.firebasestorage.app',
    measurementId: 'G-XS6HGVQTRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeUN0_-ZCgFOe7OWjPFqLQ0M2rFRn5PI',
    appId: '1:579004116235:android:9e90703b9ba94cfb82c60e',
    messagingSenderId: '579004116235',
    projectId: 'makanek-c0f6a',
    storageBucket: 'makanek-c0f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMkHu9q5c4dqmYVa1UKo7eM_mZjF88VC4',
    appId: '1:579004116235:ios:c61c0819ccb457ee82c60e',
    messagingSenderId: '579004116235',
    projectId: 'makanek-c0f6a',
    storageBucket: 'makanek-c0f6a.firebasestorage.app',
    iosClientId: '579004116235-39r1ecob66pdgqlu997vb9ufo3ifulcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.makanek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMkHu9q5c4dqmYVa1UKo7eM_mZjF88VC4',
    appId: '1:579004116235:ios:c61c0819ccb457ee82c60e',
    messagingSenderId: '579004116235',
    projectId: 'makanek-c0f6a',
    storageBucket: 'makanek-c0f6a.firebasestorage.app',
    iosClientId: '579004116235-39r1ecob66pdgqlu997vb9ufo3ifulcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.makanek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnG7H_WcRm5WbR-JM_8-purMln4mW9rl4',
    appId: '1:579004116235:web:e727425f655b70b282c60e',
    messagingSenderId: '579004116235',
    projectId: 'makanek-c0f6a',
    authDomain: 'makanek-c0f6a.firebaseapp.com',
    storageBucket: 'makanek-c0f6a.firebasestorage.app',
    measurementId: 'G-K5Z848WSP0',
  );
}
